Fix #996 - Stop alias name from flickering
mozilla/fx-private-relay pull request #1000
Opened 2021-08-06 22:45 UTC by codemist

**Flickering on hover has stopped, check demo:**
https://user-images.githubusercontent.com/13066134/128577742-0779ac4f-4082-435b-b9f8-8adf694dfbe3.mov

**Mobile:**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/13066134/128577789-8f5f39c2-49b7-45d4-8d75-9798bd110e91.png">

2021-08-06 22:49 UTC, codemist reviewed
Started a self review for clarification

2021-08-06 22:49 UTC, codemist commented on static/scss/partials/dashboard.scss
> +        width: 192px;
Magic Number specifically for the placeholder.

2021-08-06 22:49 UTC, codemist commented on static/scss/partials/main.scss
> -
Moved this into `dashboard.scss` for clarity

2021-08-06 22:49 UTC, codemist commented on static/scss/partials/main.scss
> +  background: $color-grey-10;
Opted for a lighter grey, it looks closer to the input field on Figma (lemme know if you agree!)

2021-08-10 16:48 UTC, maxxcrawford requested changes
I think this solution may be over-engineered. When testing, I tried adding a specific `max-width` to the `additional-notes` class. Please let me know your thoughts!

2021-08-11 21:10 UTC, maxxcrawford approved these changes

2021-08-11 21:11 UTC, merged