Fix #997 - Truncate long email on glocal menu
mozilla/fx-private-relay pull request #1003
Opened 2021-08-09 18:41 UTC by codemist

**Preview/Demo:**

Uploading Screen Recording 2021-08-09 at 11.39.13 AM.mov…

2021-08-09 18:47 UTC, codemist commented on static/scss/partials/glocal-menu.scss
> +  max-width: $screen-sm;
Set a max width of `$screen-sm`, which is `480px`.

2021-08-09 18:47 UTC, codemist commented on static/scss/partials/glocal-menu.scss
> +    @media screen and (max-width: 520px) {
Magic breakpoint of 520px here, which is roughly `$screen-sm` + some leg room to account for left/right padding.

2021-08-10 16:32 UTC, maxxcrawford requested changes

2021-08-10 16:32 UTC, maxxcrawford commented on static/scss/partials/glocal-menu.scss
> +      max-width: 100%;
Can you use a token here?

2021-08-10 16:32 UTC, maxxcrawford commented on static/scss/partials/glocal-menu.scss
> +    @media screen and (max-width: 520px) {
This comment applies for both this `max-width` and the `max-width: 520px` lines. 

Could you adjust the `max-width` to be a `calc()` argument of `$screen-sm` minus the padding? 

Then you could leave the breakpoint below at a standard, variable number. 



```suggestion
  width: auto;
  max-width: calc($screen-sm - $spacing-xl);

    @media screen and (max-width: $screen-sm) {
```

2021-08-10 16:32 UTC, maxxcrawford commented on static/scss/partials/glocal-menu.scss
> +    @media screen and (max-width: 520px) {
You may need to double check if `calc()` can accept Sass variables like that. I recall it messing up with standard CSS variables, maybe?

2021-08-10 21:15 UTC, codemist reviewed
@maxxcrawford

2021-08-10 21:15 UTC, codemist commented on static/scss/partials/glocal-menu.scss
> +  right: $spacing-lg;
`$spacing-lg` is `24px`, feel that this is close enough.

2021-08-10 21:15 UTC, codemist commented on static/scss/partials/glocal-menu.scss
> +  max-width: calc(#{$screen-sm} - #{$spacing-lg});
Calculating a smaller width based on Protocol tokens so that the width of the component does not overflow.

2021-08-10 21:15 UTC, codemist commented on static/scss/partials/glocal-menu.scss
> +      max-width: calc(#{$screen-sm} - #{$spacing-md} - #{$spacing-md});
This line fine-tunes the mobile view, I switched the left/right padding to a smaller `$spacing-md` (16px) value and accounted for this padding in the mobile `max-width`. Preview: https://drive.google.com/file/d/1Q-EPRZMdOfrIFSQXbC7YKEFFy_FIS4gu/view?usp=sharing

2021-08-11 19:29 UTC, maxxcrawford approved these changes

2021-08-11 19:29 UTC, merged