Check user created before premium release
mozilla/fx-private-relay pull request #1125
Opened 2021-09-23 20:11 UTC by say-yawn

# About this PR
Provide information on whether or not the user was created before the premium release to inform users on pref changes.

# Needs Follow-up
Need to make sure that the `joined_date` from the `User` Django object is actually the date user joins the Relay service AND NOT the date user joined FxA.

2021-09-28 16:51 UTC, groovecoder requested changes

2021-09-28 16:51 UTC, groovecoder commented on emails/models.py
> +        return date_created < datetime(2021, 10, 27, 18, 00)
Can we make this come from an env var so it's not hard-coded? Like, `2021-10-27` ?

2021-10-14 18:42 UTC, say-yawn commented
@groovecoder good point. That's probably a good idea. I created a subtask [here](https://mozilla-hub.atlassian.net/browse/MPP-1199) for pref behavior [ticket 1059](https://mozilla-hub.atlassian.net/browse/MPP-1059) to capture this PR but mentioning this on [ticket 1059](https://mozilla-hub.atlassian.net/browse/MPP-1059) would be a good idea too.

2021-10-18 18:58 UTC, groovecoder requested changes

2021-10-18 18:58 UTC, groovecoder commented on privaterelay/settings.py
> +PREMIUM_RELEASE_DATE = config('PREMIUM_RELEASE_DATE', str(datetime.now(timezone.utc)), cast=str)
can we go ahead and do `datetime.fromisoformat(config('PREMIUM_RELEASE_DATE', str(datetime.now(timezone.utc)), cast=str))` ? so we can just treat `settings.PREMIUM_RELEASE_DATE` as a `datetime` object elsewhere in the code?

Specifically, I'm thinking of how I'll implement "automatically opted in to data collection" after `settings.PREMIUM_RELEASE_DATE` and I think I'll change `Profile.server_storage` field to:

```
def default_server_storage_value():
    return datetime.now(timezone.utc) > settings.PREMIUM_RELEASE_DATE
...
class Profile(models.Model):
    ...
    server_storage = models.BooleanField(default=default_server_storage_value)
```

2021-10-18 21:11 UTC, groovecoder requested changes

2021-10-18 21:11 UTC, groovecoder commented on emails/tests/models_tests.py
> +            date_joined=datetime.now(timezone.utc)
```suggestion
            date_joined=datetime.fromisoformat('2021-10-18 17:00:00+00:00')
```
or this test will start failing on premium release day.

2021-10-18 21:19 UTC, merged