Add Premium Onboarding
mozilla/fx-private-relay pull request #1141
Opened 2021-09-29 16:18 UTC by maxxcrawford

Fixes MPP-1087

TO-DO: 
- [ ] Add l10n Strings
- [ ] Add logic to only show to premium users
- [ ] Add JS/dismissal functionality

2021-09-29 18:28 UTC, maxxcrawford commented
@codemist @Vinnl Tagging you both for a review even though this is in draft mode. The only thing remaining is locking in strings. :)

2021-09-29 18:33 UTC, maxxcrawford commented on static/scss/partials/onboarding.scss
> +@import "libs/protocol/css/components/zap.scss";
Adding in [zap component](https://protocol.mozilla.org/patterns/atoms/zap.html) from Protocol.

2021-09-29 18:33 UTC, maxxcrawford commented on static/scss/partials/onboarding.scss
> +    button {
Not sure if this should just be an `a` link. Depneds on Eduardo's designs TBH.

2021-09-30 15:58 UTC, maxxcrawford commented on static/scss/partials/onboarding.scss
> +    button {
Revised to a X in the top right corner.

2021-09-30 15:58 UTC, maxxcrawford commented on static/scss/partials/onboarding.scss
> +@import "libs/protocol/css/components/zap.scss";
_(That's also all the zap.svgs)_

2021-09-30 16:23 UTC, codemist requested changes
Looks good, however when I change to a mobile view the exit button stops working.

2021-09-30 18:55 UTC, maxxcrawford commented
> Looks good, however when I change to a mobile view the exit button stops working.

Great catch. It was a z-index issue.

2021-09-30 20:37 UTC, codemist approved these changes

2021-10-01 01:32 UTC, groovecoder requested changes
obligatory 1-character change request so you know I actually looked at EVERY SINGLE CHARACTER!

2021-10-01 01:32 UTC, groovecoder commented on privaterelay/templates/profile.html
> +  {% if user_profile.has_premium  %}
```suggestion
  {% if user_profile.has_premium %}
```

2021-10-04 14:50 UTC, maxxcrawford commented on privaterelay/templates/profile.html
> +  {% if user_profile.has_premium  %}
:zap:

2021-10-04 14:58 UTC, groovecoder approved these changes

2021-10-04 14:58 UTC, merged