fix mpp-1145: only exact match for short bad words
mozilla/fx-private-relay pull request #1183
Opened 2021-10-08 20:09 UTC by groovecoder

2021-10-08 23:10 UTC, pdehaan commented on emails/tests/models_tests.py
> +        assert not has_bad_words('cassandra')
Do we need a couple more tests here for the cases where we have a 4+ letter word from the bad list? If I'm reading the code/rule correctly this should still mean that a domain like "shell" would be invalid, correct?

2021-10-08 23:20 UTC, pdehaan commented on emails/models.py
> +            return True
Potentially very irrelevant, but while looking at the /emails/badwords.txt list, I noticed a few of them have trailing whitespace. I don't know django, but just wanted to confirm that somewhere is trimming the bad word list before comparing word lengths. Although I think only one of the results is 3 characters (but 4 with trailing space) and might have a slightly different behavior if trimmed or not.

```sh
cat emails/badwords.txt | grep -e "\s$"
```

2021-10-11 20:25 UTC, say-yawn requested changes
One recommendation to strip for leading or trailing white spaces.

2021-10-11 20:25 UTC, say-yawn commented on emails/models.py
> +            return True
```suggestion
        badword = badword.strip()
        if len(badword) <= 4 and badword == value:
            return True
        if len(badword) > 4 and badword in value:
            return True
```

2021-10-11 20:54 UTC, merged