Collect metrics on email replies and alias creation mpp 1279
mozilla/fx-private-relay pull request #1338
Opened 2021-11-08 20:17 UTC by say-yawn

# About this PR

2021-11-09 17:39 UTC, groovecoder reviewed
A few suggestions. Overall looking good.

2021-11-09 17:39 UTC, groovecoder commented on emails/models.py
> +            abuse_metric = AbuseMetrics.objects.create(user=self.user)
While we're here, could we clean up old `AbuseMetrics` records we don't need anymore? E.g.,
```
AbuseMetrics.objects.delete(first_recorded__lt=midnight_utc_today)
```

2021-11-09 17:39 UTC, groovecoder commented on emails/models.py
> +        return False
Bit of refactor to optimize ...

```suggestion
    def is_flagged(self):
        if not self.last_account_flagged:
            return False
        account_premium_feature_resumed = (
            self.last_account_flagged +
            timedelta(days=settings.PREMIUM_FEATURE_PAUSED_DAYS)
        )
        if datetime.now(timezone.utc) > account_premium_feature_resumed:
            # premium feature has been resumed
            return False
        # user was flagged and the premiume feature pause period is not yet over
        return True
```

2021-11-09 20:24 UTC, say-yawn commented on emails/models.py
> +        ).astimezone(timezone.utc) + timedelta(days=1)
Yup. Laughed at my own dumb butt.

2021-11-10 20:23 UTC, groovecoder requested changes

2021-11-10 20:23 UTC, groovecoder commented on emails/views.py
> +        user_profile = address.user.profile_set.first()
Why is this here? It's breaking replies.

2021-11-10 20:31 UTC, groovecoder commented on emails/views.py
> +        user_profile = address.user.profile_set.first()
This gets the `is_flagged` value in a way that keeps replies working:
```
diff --git a/emails/models.py b/emails/models.py
index 27bdb5c..7540c72 100644
--- a/emails/models.py
+++ b/emails/models.py
@@ -624,10 +624,18 @@ class Reply(models.Model):
     def address(self):
         return self.relay_address or self.domain_address

+    @property
+    def profile(self):
+        return self.address.user.profile_set.first()
+
     @property
     def owner_has_premium(self):
-        profile = self.address.user.profile_set.first()
-        return profile.has_premium
+        return self.profile.has_premium
+
+    @property
+    def owner_is_flagged(self):
+        return self.profile.is_flagged
+


 class AbuseMetrics(models.Model):
diff --git a/emails/views.py b/emails/views.py
index 9ef3a04..d96ec73 100644
--- a/emails/views.py
+++ b/emails/views.py
@@ -436,12 +436,10 @@ def _reply_allowed(from_address, to_address, reply_record):
     ):
         # This is a Relay user replying to an external sender;
         # verify they are premium
-        [from_local_portion, from_domain_portion] = stripped_from_address.split('@')
-        address = _get_address(
-                stripped_from_address, from_local_portion, from_domain_portion
-            )
-        user_profile = address.user.profile_set.first()
-        if reply_record.owner_has_premium and not user_profile.is_flagged:
+        if (
+            reply_record.owner_has_premium and
+            not reply_record.owner_is_flagged
+        ):
             # TODO: send the user an email
             # that replies are a premium feature
             return True
```

2021-11-10 20:33 UTC, groovecoder requested changes

2021-11-10 20:33 UTC, groovecoder commented on emails/views.py
> +        with transaction.atomic:
```suggestion
        with transaction.atomic():
```

2021-11-10 21:07 UTC, groovecoder approved these changes

2021-11-10 21:51 UTC, merged