Allow manually creating custom aliases
mozilla/fx-private-relay pull request #1485
Opened 2022-01-20 11:49 UTC by Vinnl

# New feature description

This allows users to create custom aliases themselves, without having to send an email to it.

# Screenshot (if applicable)

How about a video?

https://user-images.githubusercontent.com/4251/150332894-7319960d-621b-412e-88b3-4b6645aa3e49.mp4

# How to test

1. Log in using an account that has Premium _and_ has a custom subdomain.
2. Click "Generate new alias".
3. Verify that a menu pops up, through which you can create your own custom alias.
4. Also make sure that a non-Premium user, or a Premium user without a custom subdomain, just has a regular button that directly creates a random alias.

# Checklist

- [x] l10n dependencies have been merged, if any. - Most of them, but I forgot two unfortunately: https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/55
- [ ] All acceptance criteria are met. - It also says it should shop up on top, but alias sorting I think is a separate PR that might conflict with https://github.com/mozilla/fx-private-relay-add-on/pull/242, so I left that for a potential follow-up PR.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-01-20 12:27 UTC, Vinnl commented on .eslintignore
> +frontend/out
I'm sorry, I snuck in an unrelated change, but this directly might be present if you've checked out the `react-experiment` branch in the past, and it's annoying if ESLint tries to lint it.

2022-01-23 21:25 UTC, maxxcrawford requested changes
Nice feature build-out! I'm excited to see this get built out. 

- Keyboard accessibility notes: 
  - Add :focus/hover state for sub-items when the alias create panel is open (from keyboard only)
  - When the modal opens, you may focus on that input

Blocking concern: When I tried to create the same alias twice, I did not get any error state/messaging — it just didn't work/submit. Can you add sort of error state?

2022-01-24 15:55 UTC, Vinnl commented on privaterelay/templates/includes/dashboard-filter.html
> +<script src="{% static 'js/custom-alias-picker.js' %}"></script>
Excellent idea: ba6df120

2022-01-24 15:56 UTC, Vinnl commented on privaterelay/templates/includes/dashboard-filter.html
> +                    class="blue-btn-states dash-create-new-relay flx al-cntr jst-cntr"
075975fa

2022-01-24 15:56 UTC, Vinnl commented on privaterelay/templates/includes/dashboard-filter.html
> +                    <div class="js-dash-create-new-alias-menu-popup generate-new-alias-menu-popup hidden">
4f2542fb

2022-01-24 15:56 UTC, Vinnl commented on static/js/app.js
> +    generateAliasMenuPopup.classList.toggle("hidden");
4f2542fb

2022-01-24 15:56 UTC, Vinnl commented on static/js/app.js
> +      mainWrapper.style.marginTop = 0;
I didn't change this code; merely fixed the indentation. It was introduced in #1326. That said, I assume it's the same as the difference between

```css
margin-top: 0;
```

and

```css
margin-top: 0px
```

which are equivalent, and for which we don't have a rule in stylelint mandating one or the other. So for now, I think the answer would be: not necessarily :)

2022-01-24 15:56 UTC, Vinnl commented on static/js/custom-alias-picker.js
> +            formSubmitRequest: async (_e) => {
Nope (hence the `_` prefix), I left it in as a nod that it's a regular submit event listener, but might as well remove it: f9185f93

2022-01-24 15:56 UTC, Vinnl commented on static/scss/partials/main.scss
> +    border-radius: 4px;
7e91b12a

2022-01-24 15:56 UTC, Vinnl commented on static/scss/partials/main.scss
> +    margin-left: 1em;
fa41c08d

2022-01-24 16:09 UTC, Vinnl commented
@maxxcrawford Whoops, I did actually add an error state, but called a non-existent method (`customAliasPicker.modal.showError` rather than `customAliasPicker.showError`). If only there was a tool that would warn me of such things! :P 75bfc4cc

I'm not sure what you mean about adding focus states though - I think they all already had one? See screencast below.

https://user-images.githubusercontent.com/4251/150819853-0e4c69c6-3ed2-4dcf-a408-a94626c5b5a4.mp4

2022-01-25 22:11 UTC, maxxcrawford commented on static/js/custom-alias-picker.js
> +            formSubmitRequest: async (_e) => {
Got'cha! That nod makes sense.

2022-01-25 22:15 UTC, maxxcrawford approved these changes
🏁 Off to the races!

2022-01-26 09:28 UTC, merged