Add placeholder for custom aliases
mozilla/fx-private-relay pull request #1508
Opened 2022-01-28 13:06 UTC by Vinnl

This PR fixes #1505.

How to test: when logged in as a Premium user with a custom subdomain, generate a new custom alias via the "Generate new alias" menu. When the input field is not focused, you should see an example of the alias you could create.

- [x] l10n dependencies have been merged, if any.
- [x] I've added a unit test to test for potential regressions of this bug (or this is a front-end change, where we don't yet have unit test infrastructure).
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-01-28 19:45 UTC, maxxcrawford requested changes
This needs to be caught up with https://github.com/mozilla/fx-private-relay/pull/1507 to be tested. It currently does not work if I don't have a subdomain registered.

2022-01-28 19:47 UTC, maxxcrawford commented
Note that it should be good to go otherwise! I was able to verify this with a prem account that had the subdomain already registered.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/2692333/151611732-10f31dbe-fae4-4b8c-962b-2f3704c4dee9.png">

2022-01-31 09:41 UTC, Vinnl commented
@maxxcrawford :+1: rebased on `main`!

2022-01-31 21:38 UTC, maxxcrawford approved these changes
Ready to go!

2022-02-01 11:06 UTC, merged