Update attachment size limit copy from 150KB to 25MB
mozilla/fx-private-relay pull request #1548
Opened 2022-02-16 19:36 UTC by codemist

**Under: “I’m not getting messages from my aliases.”:**

- Changed “The email forwarded has an attachment larger than ⁨⁨150⁩ ⁨KB⁩⁩” to “The email forwarded has an attachment larger than ⁨⁨25 MB.”

**Under: Will ⁨Firefox Relay⁩ forward emails with attachments?**
- Changed “We now support attachment forwarding. However, there is a ⁨⁨150⁩ ⁨KB⁩⁩ limit for email forwarding using ⁨Relay⁩. Any emails larger than ⁨⁨150⁩ ⁨KB⁩⁩ will not be forwarded.” to “We now support attachment forwarding. However, there is a ⁨⁨25 MB⁩⁩ limit for email forwarding using ⁨Relay⁩. Any emails larger than ⁨⁨25 MB⁩⁩ will not be forwarded.”

**Under Update relay dashboard:**

Changed “⁨Firefox Relay⁩ supports email forwarding (including attachments) of email up to ⁨⁨150⁩ ⁨KB⁩⁩ in size” to “⁨Firefox Relay⁩ supports email forwarding (including attachments) of email up to ⁨⁨25 MB⁩⁩ in size”

# Screenshot (if applicable)

![image](https://user-images.githubusercontent.com/13066134/154341882-554025fa-594c-4d27-bb84-d1694b6ff016.png)
![image](https://user-images.githubusercontent.com/13066134/154341993-2eb65200-43c7-46cc-b921-317ec41ea983.png)
![image](https://user-images.githubusercontent.com/13066134/154342104-e9fcf4f2-afe7-4e29-ac1f-5f9c0d4ffa44.png)

# How to test
Check FAQ and Dashboard section, and make sure there are no mentions of a 150KB limit, but 25MB instead.

# Checklist

- [ ] l10n dependencies have been merged, if any.
- [ ] All acceptance criteria are met.
- [ ] I've added or updated relevant docs in the docs/ directory.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-02-16 19:56 UTC, pdehaan commented
```sh
git grep "'150'" | cat

emails/templates/emails/wrapped_email.html:                      {% ftlmsg 'forwarded-email-header-attachment' faq_link=faq_link size='150' unit='KB' as forwarded_email_wrap_attachment %}
privaterelay/templates/includes/alias-stats.html:      <strong>{% ftlmsg 'profile-forwarded-note' %}</strong> {% ftlmsg 'profile-forwarded-note-copy' size='150' unit='KB' %}
```

```sh
git grep "150KB" | cat
emails/views.py:            'of email up to 150KB in size. To learn more visit {site}{faq}\n'
emails/views.py:        max_size=150*1000,  # 150KB max from SES

2022-02-16 20:16 UTC, codemist commented
@pdehaan Hmmm, I following the ticket on Jira but I'll let Tony know there are other instances of 150KB

2022-02-22 19:55 UTC, maxxcrawford requested changes
@pdehaan Thanks for looking out! 

@codemist I recommend revising the following two items in this PR: 
- `emails/templates/emails/wrapped_email.html:53`
- `privaterelay/templates/includes/alias-stats.html:17`

The other items (in the `*.py` files) are still blocking on the feature, but do not need to be addressed in this PR. That SVG item can be ignored (as it doesn't apply).

2022-02-24 21:59 UTC, maxxcrawford approved these changes
LGTM! Ready to land at @tcinotto's directive.

2022-02-24 22:41 UTC, merged