Add metric for replies mpp 1146
mozilla/fx-private-relay pull request #1900
Opened 2022-05-05 22:06 UTC by say-yawn

# About this PR
Since we offer premium feature to reply to relayed emails, we want to separately increment the number of replies made instead of grouping it with forwarded.

# Acceptance Criteria
- [ ] Client side code can get number of replied per Relay address
- [ ] Client side code can get number of replied per Domain address
- [ ] Client side can get total number of replied per profile
- [ ] Forward metric is NO longer incremented when a user responds to email

#
[MPP-1146](https://mozilla-hub.atlassian.net/browse/MPP-1146)

2022-05-06 16:28 UTC, jwhitlock requested changes
Thanks @say-yawn! I like the more precise metric.

Required change: When creating the `DeletedAddress` for a `RelayAddress` and a `DomainAddress`, please copy `num_replied` as well.

2022-05-06 16:28 UTC, jwhitlock commented on emails/models.py
> +        address.last_used_at = datetime.now(timezone.utc)
praise: I'm going to use this instead of `datetime.now(tz=timezone.utc)`, saves 3 characters!

2022-05-06 16:29 UTC, jwhitlock commented
Hmm, which probably means adding this field to the `DeletedAddress` as well...

2022-05-10 19:09 UTC, jwhitlock requested changes
Thanks @say-yawn! A few more changes are needed to get the profile API working.

2022-06-06 21:50 UTC, say-yawn commented on emails/models.py
> +            self.num_email_replied_in_deleted_address
Nice catch! I caught some additional issues with using the `aggregate` function. Thanks for recommending this fix.

2022-06-07 15:39 UTC, jwhitlock approved these changes
Thanks @say-yawn! Before merging, can you run `black` to update the formatting?

I tried this in my local development environment, and it worked well:

* Sent two emails to two relay aliases. Forwarded count increments by two.
* Reply to the emails. http://127.0.0.1:8000/api/v1/profiles/ shows `"emails_replied": 1` then `2`.
* Delete one of the aliases. `"emails_replied"` remains at `2`. However, forwarded count drops (issue #1971).
* Continue the conversation on the remaining alias, getting `"emails_replied"` to `3`.

I think this is mergable before the UI to report it.

2022-06-07 15:39 UTC, jwhitlock commented on api/serializers.py
> +            'emails_replied',
Thanks, it is in the API now.

Do you plan to add `"num_replied"` to the `domainaddress` and `relayaddress` APIs as well?

2022-06-07 15:39 UTC, jwhitlock commented on emails/migrations/0043_add_num_replied_field_on_addresses.py
> +        ('emails', '0042_domainaddress_used_on'),
The single quotes will be replaced by double-quotes w/ `black`

2022-06-07 15:39 UTC, jwhitlock commented on emails/tests/models_tests.py
> +
`black` will clean up some whitespace in this section.

2022-06-08 17:14 UTC, merged