MPP-2263 Phone Numbers tab redirect update
mozilla/fx-private-relay pull request #2328
Opened 2022-08-10 17:38 UTC by lloan

This PR fixes  MPP-2263
 

# New feature description

Clicking on the “Phone Numbers” tab redirected the user to the “Verify your phone number” screen instead of the purchase flow. This PR should make it so clicking on the tab redirects the user to the “Verify your phone number” screen of the flow instead.

# Screenshot (if applicable)

Not applicable.

# How to test

- Sign in into a Premium Firefox Relay account
- Go to the Relay dashboard
- Click on the “Phone Numbers” tab in the site header
- Observe the results

# Checklist

- [ ] l10n changes have been submitted to the l10n repository, if any.
- [ ] All acceptance criteria are met.
- [ ] I've added or updated relevant docs in the docs/ directory.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-08-10 19:29 UTC, groovecoder requested changes
This looks like it changes the phone navigation item to go straight to the "purchase phones" page on SubPlat. But we *HAVE* our own phone landing page that should be displaying at `/phone` for users who have not bought phones yet.

2022-08-10 19:31 UTC, lloan commented
> 

It definitely does that! Completely fumbled this one - I'll look for the link to that phone page and update it - should be a quick update. Thanks a ton!

2022-08-10 22:24 UTC, groovecoder commented
Uplifting from Slack ...

yeah, there’s definitely a page in there. that’s the bug - instead of that page showing up, the app jumps straight to “verify your phone number”
https://github.com/mozilla/fx-private-relay/blob/5b5cf57e2f567fc656167e1d8a018f7b29df82e8/frontend/src/components/phones/onboarding/PhoneOnboarding.tsx#L27-L30 and https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/phones/onboarding/PurchasePhonesPlan.tsx

...

maybe `if (!profiles.data?.[0].has_phone) {` is evaluating to `true` somehow?

2022-08-11 18:25 UTC, lloan commented
> Uplifting from Slack ...
> 
> yeah, there’s definitely a page in there. that’s the bug - instead of that page showing up, the app jumps straight to “verify your phone number”
> 
> https://github.com/mozilla/fx-private-relay/blob/5b5cf57e2f567fc656167e1d8a018f7b29df82e8/frontend/src/components/phones/onboarding/PhoneOnboarding.tsx#L27-L30
> 
> and https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/phones/onboarding/PurchasePhonesPlan.tsx
> ...
> 
> maybe `if (!profiles.data?.[0].has_phone) {` is evaluating to `true` somehow?

I opted with having this logic with other similar logic within the `phone.page.tsx` - conditional rendering that deals with similar stuff. We just check if the user has purchased a phone - if they haven't, we render the component that shows the phone plan information + ability for user to purchase it (button). 

I tested with multiple accounts - new accounts - shows purchase plans if user has not purchased a phone. I did notice that when I clicked the button and purchased a phone plan, it also comes with Relay Premium - is that correct?

2022-08-11 19:27 UTC, groovecoder commented
> I did notice that when I clicked the button and purchased a phone plan, it also comes with Relay Premium - is that correct?

Yup, that's correct.

2022-08-11 19:29 UTC, groovecoder requested changes

2022-08-11 19:29 UTC, groovecoder commented on frontend/src/pages/phone.page.tsx
> +  // show the phone plan purchase page if the user has no phone number
```suggestion
  // show the phone plan purchase page if the user has not purchased phone product
```

2022-08-11 19:44 UTC, groovecoder approved these changes

2022-08-11 19:49 UTC, groovecoder commented
It's beautiful.
![image](https://user-images.githubusercontent.com/71928/184226750-e3bb01d0-b039-4531-8d07-1b835ee399f7.png)

2022-08-11 19:49 UTC, merged