MPP-2286 Prevent verified numbers from doing verification process again.
mozilla/fx-private-relay pull request #2359
Opened 2022-08-19 18:37 UTC by lloan

This PR fixes MPP-2286
 

# New feature description

Show error state when a user tries to register a phone number that is already registered for relay phone masking.

This adds an additional check - is the phone number already verified? This helps prevent verification codes from being sent to numbers that are already verified. 

# Screenshot (if applicable)

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/3924990/185684949-b4d88b4b-2ef2-45cb-b385-1c7486f7dff2.png">

# How to test

Have an existing verified phone number. Try using another account to verify the same real phone number. You should get an error. 

# Checklist

- [ ] l10n changes have been submitted to the l10n repository, if any.
- [ ] All acceptance criteria are met.
- [ ] I've added or updated relevant docs in the docs/ directory.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-08-19 19:14 UTC, groovecoder requested changes
We should add a test for this. Do you want to do that, or I can.

2022-08-19 19:17 UTC, lloan commented
> We should add a test for this. Do you want to do that, or I can.

You can probably knock it out a lot faster than me fumbling - I'll use the test you write here to learn from and then the next time I write something, it will come with a test :)!

2022-08-20 13:41 UTC, groovecoder commented
Added test in https://github.com/mozilla/fx-private-relay/pull/2359/commits/cbc412a206f04519b53ff63dea8c3dc43c437bc5.

2022-08-20 13:41 UTC, groovecoder approved these changes

2022-08-20 13:41 UTC, merged