Use a table for tabular log data
mozilla/fx-private-relay pull request #2384
Opened 2022-08-23 13:16 UTC by Vinnl

Otherwise screen readers will announce the entire <li> as a single
item, disconnected from the headings. (If you're on MacOS, try enabling VoiceOver, and compare how it reads the log data before this change and after this change.)

How to test: the call and SMS log should be roughly the same, but when inspecting it through a screen reader, the separate cells should be read separately, with the associated table headings announced as well.

- [x] l10n changes have been submitted to the l10n repository, if any.
- [ ] I've added a unit test to test for potential regressions of this bug. - N/A
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-08-23 14:24 UTC, codemist requested changes
I just tested this on my local and the mobile view of the panel disappeared. May be missing some of the media 

https://user-images.githubusercontent.com/13066134/186183350-79520f0d-a2f5-44a4-9ba5-2834c2073ea1.mov

2022-08-24 09:35 UTC, Vinnl commented
Hmm, looks like something went wrong when I tried to split this out from my other work - rebasing on `main` fixed it.

2022-08-24 14:01 UTC, codemist commented
I checked out this branch again, rebased and I'm still getting a blank mobile view: https://github.com/mozilla/fx-private-relay/pull/2384

2022-08-25 12:59 UTC, Vinnl commented
So weird @codemist! How about now? There was a `display: none` that inadvertently also applied to the first element in the log, so maybe your log just included a single line?

2022-08-25 19:31 UTC, codemist commented
Works for me now! 
<img width="645" alt="image" src="https://user-images.githubusercontent.com/13066134/186752116-78ecf5d5-76da-4802-8514-6ef1f89a68da.png">

2022-08-25 19:31 UTC, codemist approved these changes

2022-08-25 19:31 UTC, merged