Add custom dimension to distinguish add-on telemetry from website traffic
mozilla/fx-private-relay pull request #2810
Opened 2022-11-15 21:39 UTC by maxxcrawford

This PR fixes #<issue ID>.

How to test:

- [ ] l10n changes have been submitted to the l10n repository, if any.
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] I've added or updated relevant docs in the docs/ directory.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2022-11-15 21:47 UTC, maxxcrawford commented on privaterelay/views.py
> +        dimension7=request_data.get("dimension7", "website"),
note: I did not leave the default as `None`, but we are not using this for website-routing GA traffic. In the future, if we do this, we would want to set it to "website".

2022-11-15 23:02 UTC, groovecoder requested changes

2022-11-15 23:02 UTC, groovecoder commented on privaterelay/views.py
> +    # used to determine which where the traffic is coming from: website (default), add-on or app
```suggestion
    # used to determine where the ping is coming from: website (default), add-on or app
```

2022-11-16 21:27 UTC, groovecoder approved these changes

2022-11-16 21:55 UTC, merged