MPP-3078: Rewrite `_handle_bounce` to log more data
mozilla/fx-private-relay pull request #3404
Opened 2023-05-10 16:30 UTC by jwhitlock

When looking at the data for bounces for MPP-3078, the logs are missing the bounce type and subtype from AWS. This is probably a better method for determining what we should do for bounces than parsing the diagnostic code, which is meant for an email admin to read.

This PR rewrites `_handle_bounce` to move metrics and logging to the end of the function, and to augment them with more data.

The counter "email_bounce" now has tags 'bounce_type', 'bounce_subtype', 'user', and 'relay_action'. The type and sub-type are lowercased. The counter will be incremented for each recipient identified by AWS, or once if no recipients. Previously, this was incremented once per bounce notification, with no tags.

The new log "bounce_notification" has the same data, except the type and subtype are not lowercase. It also includes the data from the bounce recipient 'bounce_action', 'bounce_status', and 'bounce_diagnostic'. If there is more undocumented data, it is in 'bounce_extra'. There is also 'domain' for the user's domain.

The log "bounced recipient domain: {domain}" is still emitted, but marked as legacy. It can be removed in Q4 2023, when we have a full backlog of "bounce_notification" logs.

Some unused metrics have been removed:
* The counter "email_bounce_relay_user_gone" is replaced with the counter "email_bounce" with tag "user=missing".
* The counter "email_bounce_Permanent_General" is replaced with the counter "email_bounce" with tag "bounce_type=permanent", "bounce_subtype=general". Other similar tags that embedded the type and subtype in the name are replaced in the same way.

The handler no longer returns a 404 on the first missing user, but continues processing the recipient list. This is not expected to have an impact, since we forward emails to a single recipient.

# To Test
I did not run this against live data, but relied on the existing tests, which did not change.

1. Edit `.env` to enable statsd logs:
        DJANGO_STATSD_ENABLED=True
        STATSD_DEBUG=True
3. Run `pytest emails/tests/views_tests.py::BounceHandlingTest -sv`, to run the bounce tests in verbose mode without capturing output.

Before this change, I got output for the first test like this:

```
emails/tests/views_tests.py::BounceHandlingTest::test_sns_message_with_hard_bounce Creating test database for alias 'default'...
{"Timestamp": 1683735414647800064, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.lan", "EnvVersion": "2.0", "Severity": 6, "Pid": 7708, "Fields": {"msg": "METRICS|2023-05-10 16:16:54|incr|fx.private.relay.sns_inbound_Notification_Received|1|"}}
{"Timestamp": 1683735414648381952, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.lan", "EnvVersion": "2.0", "Severity": 6, "Pid": 7708, "Fields": {"msg": "METRICS|2023-05-10 16:16:54|incr|fx.private.relay.email_bounce|1|"}}
{"Timestamp": 1683735414648477952, "Type": "eventsinfo", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.lan", "EnvVersion": "2.0", "Severity": 6, "Pid": 7708, "Fields": {"action": "failed", "status": "5.1.1", "diagnosticCode": "Amazon SES did not send the message to this address because it is on the suppression list for your account. For more information about removing addresses from the suppression list, see the Amazon SES Developer Guide at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-email-suppression-list.html", "msg": "bounced recipient domain: test.com"}}
{"Timestamp": 1683735414649171968, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.lan", "EnvVersion": "2.0", "Severity": 6, "Pid": 7708, "Fields": {"msg": "METRICS|2023-05-10 16:16:54|incr|fx.private.relay.email_bounce_Permanent_OnAccountSuppressionList|1|"}}
{"Timestamp": 1683735414649914112, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.lan", "EnvVersion": "2.0", "Severity": 6, "Pid": 7708, "Fields": {"msg": "METRICS|2023-05-10 16:16:54|timing|fx.private.relay.s3_remove_message_from|0.000666000232740771|"}}
PASSED
...
```

```
emails/tests/views_tests.py::BounceHandlingTest::test_sns_message_with_hard_bounce Creating test database for alias 'default'...
{"Timestamp": 1683734579199550976, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.local", "EnvVersion": "2.0", "Severity": 6, "Pid": 7052, "Fields": {"msg": "METRICS|2023-05-10 16:02:59|incr|fx.private.relay.sns_inbound_Notification_Received|1|"}}
{"Timestamp": 1683734579201264128, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.local", "EnvVersion": "2.0", "Severity": 6, "Pid": 7052, "Fields": {"msg": "METRICS|2023-05-10 16:02:59|incr|fx.private.relay.email_bounce|1|#bounce_type:permanent,bounce_subtype:onaccountsuppressionlist,user:found,relay_action:hard_bounce"}}
{"Timestamp": 1683734579201334016, "Type": "eventsinfo", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.local", "EnvVersion": "2.0", "Severity": 6, "Pid": 7052, "Fields": {"bounce_type": "Permanent", "bounce_subtype": "OnAccountSuppressionList", "bounce_action": "failed", "bounce_status": "5.1.1", "bounce_diagnostic": "Amazon SES did not send the message to this address because it is on the suppression list for your account. For more information about removing addresses from the suppression list, see the Amazon SES Developer Guide at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-email-suppression-list.html", "user": "found", "relay_action": "hard_bounce", "domain": "test.com", "msg": "bounce_notification"}}
{"Timestamp": 1683734579201404928, "Type": "eventsinfo", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.local", "EnvVersion": "2.0", "Severity": 6, "Pid": 7052, "Fields": {"action": "failed", "status": "5.1.1", "diagnosticCode": "Amazon SES did not send the message to this address because it is on the suppression list for your account. For more information about removing addresses from the suppression list, see the Amazon SES Developer Guide at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-email-suppression-list.html", "msg": "bounced recipient domain: test.com"}}
{"Timestamp": 1683734579201613056, "Type": "markus", "Logger": "fx-private-relay", "Hostname": "MacBook-Pro-2.local", "EnvVersion": "2.0", "Severity": 6, "Pid": 7052, "Fields": {"msg": "METRICS|2023-05-10 16:02:59|timing|fx.private.relay.s3_remove_message_from|0.0005840001904289238|"}}
PASSED
...
```

The changes:
* Counter `fx.private.relay.sns_inbound_Notification_Received` is the same
* Counter `fx.private.relay.email_bounce` now has tags:
    - `bounce_type:permanent`
    - `bounce_subtype:onaccountsuppressionlist`
    - `user:found`
    - `relay_action:hard_bounce`
* New `eventsinfo` log with data:
    ```json
    {
      "bounce_type": "Permanent",
      "bounce_subtype": "OnAccountSuppressionList",
      "bounce_action": "failed",
      "bounce_status": "5.1.1",
      "bounce_diagnostic": "Amazon SES did not send the message to this address because it is on the suppression list for your account. For more information about removing addresses from the suppression list, see the Amazon SES Developer Guide at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-email-suppression-list.html",
      "user": "found",
      "relay_action": "hard_bounce",
      "domain": "test.com",
      "msg": "bounce_notification"
    }
    ```
* Same `eventsinfo` log with data:
    ```json
    {
      "action": "failed",
      "status": "5.1.1",
      "diagnosticCode": "Amazon SES did not send the message to this address because it is on the suppression list for your account. For more information about removing addresses from the suppression list, see the Amazon SES Developer Guide at https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-email-suppression-list.html",
      "msg": "bounced recipient domain: test.com"
    }
    ```
* metric `fx.private.relay.email_bounce_Permanent_OnAccountSuppressionList` removed, data is  [...]

2023-05-10 18:58 UTC, groovecoder requested changes
Only did the code review so far - requesting just a couple small changes. I'll do testing next.

2023-05-10 18:58 UTC, groovecoder commented on emails/views.py
> +        if "spam" in data["bounce_diagnostic"].lower():
praise: woohoo! Thanks for digging in and finding this much better field.

2023-05-10 19:28 UTC, jwhitlock commented on emails/views.py
> +    https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html#bounce-object
I agree, moved up

2023-05-10 19:29 UTC, jwhitlock commented on emails/views.py
> +    * domain - User's domain, if an address was given
I've expanded the comment, and made some other docstring tweaks.

I've also changed "user" to "user_match", which seems less likely to be confused with a username.

2023-05-11 14:38 UTC, groovecoder approved these changes

2023-05-11 14:58 UTC, merged