MPP-3404 - Retire resender flag
mozilla/fx-private-relay pull request #3891
Opened 2023-09-13 20:56 UTC by jwhitlock

The `resender_headers` flag was turned on for everyone in production on September 5, 2023, and has been mostly error free. This PR removes it from the code, and removes code paths where it is off.

# Checklist (Definition of Done)
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2023-09-14 14:41 UTC, groovecoder requested changes
Small but important code doc change. Everything else looks good!

2023-09-14 14:41 UTC, groovecoder commented on emails/utils.py
> -
change (blocking, though not part of this particular code change): When I looked for the corresponding code in the new `generate_from_header` function, I saw this:
```
      # Truncate the to 71 characters, so the sender portion fits on the first
```

Looks like it should say "Truncate the display_name to 71 characters ..."?

2023-09-14 20:14 UTC, jwhitlock commented
Good catch!

As long as we're touching that code, I added an exception handler to capture data for MPP-3407 and MPP-3417, where some `From:` addresses are causing exceptions. The handler logs the address and re-raises the exception, so no logic change (yet).

2023-09-15 17:21 UTC, groovecoder approved these changes
Nice. thanks for adding more tests for more possible scenarios.

2023-09-15 17:27 UTC, merged