MPP-3599 & MPP-3602: Free user onboarding bug fixes
mozilla/fx-private-relay pull request #4170
Opened 2023-11-29 13:00 UTC by lloan

This PR fixes MPP-3599 and MPP-3602
 

# New feature description

On the second step of the Free onboarding, the “See how forwarding works” button text has an extra “+”. This removes that.

No animation is triggered when completing the onboarding process. This animation is now triggered once user completes onboarding. 

# Screenshot (if applicable)

 Second step - removal of + 
 
![image](https://github.com/mozilla/fx-private-relay/assets/3924990/74ff0925-950d-400c-9545-c6b9233e0bbc)

Confetti animation

![image](https://github.com/mozilla/fx-private-relay/assets/3924990/9c7ac95a-1c49-4ff5-8352-44649273bafd)

# How to test

Free user account with `onboarding_free_state` set to 0. 
`free_user_onboarding` flag turned on.

# Checklist (Definition of Done)
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] I've added or updated relevant docs in the docs/ directory
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] l10n changes have been submitted to the l10n repository, if any.

2023-11-29 22:16 UTC, rafeerahman requested changes
Looks good, just one comment that needs attention.

2023-11-29 22:16 UTC, rafeerahman commented on frontend/src/pages/accounts/profile.page.tsx
> +        profile.onboarding_free_state < freeOnboardingCelebrationStep && (
(Blocking) With the changes in #4171, this triggers the confetti animation once for existing free users who sign in normally (did not come from onboarding).

2023-11-30 15:38 UTC, rafeerahman approved these changes
Works as intended now!

One more thing, I believe we removed the double hyphens in the L10n repo, so the one here and possibly others are grabbing the strings from only pendingTranslations. We should change these in the pendingTranslations.ftl to remove the double hyphens, and in the files they are being used in.
https://github.com/mozilla/fx-private-relay/blob/4e4ebae7bd74b35ba601e1d810a25eaeca33404c/frontend/src/components/dashboard/FreeOnboarding.tsx#L108C7-L108C7

2023-11-30 15:50 UTC, lloan commented
> Works as intended now!
> 
> One more thing, I believe we removed the double hyphens in the L10n repo, so the one here and possibly others are grabbing the strings from only pendingTranslations. We should change these in the pendingTranslations.ftl to remove the double hyphens, and in the files they are being used in. https://github.com/mozilla/fx-private-relay/blob/4e4ebae7bd74b35ba601e1d810a25eaeca33404c/frontend/src/components/dashboard/FreeOnboarding.tsx#L108C7-L108C7

@rafeerahman opening ticket to address that in separate PR. I thought that was addressed with this work [here](https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/163#pullrequestreview-1723714352).

2023-11-30 16:06 UTC, merged