MPP-3698: Enable `mypy --check-untyped-def --no-implicit-reeexport` across code
mozilla/fx-private-relay pull request #4347
Opened 2024-01-26 17:12 UTC by jwhitlock

*Work in Progress* - This needs to be rebased after PR #4321. I'll add more details then.

For MPP-3698, I updated the code so both `--check-untyped-def` is used across our code. This means that code without type annotations is checked by `mypy` rather than skipped, and finds errors like not considering `None` or other alternate return types.

This is a big PR, but the changes themselves are small.

2024-01-26 21:58 UTC, jwhitlock commented
PR #4321 is merged, this is ready for review.

2024-01-29 16:28 UTC, groovecoder requested changes
One blocking question about returning `401` status code that's very important to get right because Firefox clients change their behavior based on that status code.

2024-01-29 16:28 UTC, groovecoder commented on privaterelay/settings.py
> +from typing import Any, Literal, Optional, TYPE_CHECKING, cast, get_args
suggestion (non-blocking): change L719 to `sentry_release: str | None` and remove import of `Optional`

2024-01-29 16:28 UTC, groovecoder commented on privaterelay/settings.py
>  STATSD_PREFIX = config("DJANGO_STATSD_PREFIX", "fx.private.relay")
question (non-blocking): I can't figure out why we declare the type of `STATSD_ENABLED` but none of these other ones? Does the default value in the `config` call effectively declare the type for `mypy`? I can't tell what the pattern is of when we do/don't declare the type of a `settings` variable.

2024-01-29 16:28 UTC, groovecoder commented on privaterelay/tests/fxa_utils_tests.py
> +@override_flag("free_phones", active=True)
praise: nice clean-up.

2024-01-29 16:28 UTC, groovecoder commented on privaterelay/tests/mgmt_sync_phone_related_dates_on_profile_tests.py
>      free_phones_flag.save()
suggestion (non-blocking): this block is used at least twice. Can we move this logic into a `get_user_free_phones()` helper function?

2024-01-29 16:28 UTC, groovecoder commented on pyproject.toml
> -]
praise: woohoo!! look at all these modules with better type-checking now!

2024-01-29 17:55 UTC, jwhitlock reviewed
Thanks for the quick review @groovecoder! I've answered some questions, and made two suggested changes:

* Removed `Optional` from `privaterelay/settings.py`
* Added `create_free_phones_flag_for_user` helper

2024-01-29 20:17 UTC, groovecoder commented on api/authentication.py
> +        raise AuthenticationFailed("FXA returned active: False for token.")
Thanks for the detailed info! That, and the fact that `test_inactive_token_responds_with_401` test makes sure the `401` is returned in the right case, and that test is still passing, makes me non-blocking on this again!

2024-01-29 20:22 UTC, groovecoder approved these changes

2024-01-29 21:24 UTC, say-yawn commented on api/authentication.py
> +        raise AuthenticationFailed("FXA returned active: False for token.")
I found out that `code` is returned in response data like:
```python
> response.data
{'detail': ErrorDetail(string='FXA returned active: False for token.', code='authentication_failed')}
```
And I checked in the [Firefox code](https://searchfox.org/mozilla-central/rev/3c72de9280ec57dc55c24886c6334d9e340500e8/toolkit/components/satchel/integrations/FirefoxRelay.sys.mjs#108) @groovecoder mentioned and it does not refer to `code` in the data details. So I also think we are good.

2024-01-29 23:03 UTC, merged