MPP-3786: Add type hints, make changes for browsable API
mozilla/fx-private-relay pull request #4590
Opened 2024-04-11 17:00 UTC by jwhitlock

Make changes to make `drf_spectacular` a bit happier.

# How to test:

* Run `./manage.py check --deploy` on `main`
* Run `./manage.py check --deploy` on this branch

2024-04-15 15:57 UTC, groovecoder requested changes
question (blocking): are you sure it's the `drf_spectacular.W002` warnings that are supposed to go away? When I ran the `check` on this branch, all the `drf_spectacular.W001` warnings went away, but the `W002` warnings are still there.

2024-04-15 16:00 UTC, jwhitlock commented
🤦 yep, you are correct, it is the `W001` warnings that go away. I'll fix the comment.

2024-04-16 22:51 UTC, groovecoder approved these changes

2024-04-16 22:51 UTC, groovecoder commented on api/schema.py
> +"""Schema Extensions for drf-spectacular"""
praise TIL: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

2024-04-17 15:37 UTC, merged