switch from jwt to PyJWT
mozilla/fx-private-relay pull request #695
Opened 2020-09-29 13:17 UTC by groovecoder

2020-09-29 13:51 UTC, groovecoder commented
Note: this is causing https://sentry.prod.mozaws.net/operations/fx-private-relay-dev/issues/9682934/activity/?query=is%3Aunresolved until I figure out how exactly to parse and decode the FXA verifying public key.

2020-09-29 20:02 UTC, groovecoder commented
Okay, I finally got this into a state where the branch worked on dev.fxprivaterelay.nonprod.cloudops.mozgcp.net. Ready for code review too.

2020-09-30 18:41 UTC, say-yawn requested changes
Minor changes

2020-09-30 18:41 UTC, say-yawn commented on privaterelay/views.py
> +        return authentic_jwt
```suggestion
```
return handled by outer `return` on line 168

2020-09-30 18:56 UTC, groovecoder commented on privaterelay/views.py
> +            raise Exception("Could not authenticate JWT with FXA key.")
I think I started that way, but I had to refactor the retry and raise logic "up" into a containing function, and created the new specific `_verify_jwt_with_fxa_key` function so I could call it twice without duplicating all the code inside it. E.g., the code started like this:
```python
def _authenticate_fxa_jwt(req_jwt):
    private_relay_config = apps.get_app_config('privaterelay')
    social_app = SocialApp.objects.get(provider='fxa')
    authentic_jwt = None
    for verifying_key in private_relay_config.fxa_verifying_keys:
        if verifying_key['alg'] == 'RS256':
            verifying_key = jwt.algorithms.RSAAlgorithm.from_jwk(
                json.dumps(verifying_key)
            )
            authentic_jwt = jwt.decode(
                req_jwt,
                verifying_key,
                audience=social_app.client_id,
                algorithms=['RS256']
            )

    if not authentic_jwt:
        # FXA key may be old? re-fetch FXA keys and try again
        private_relay_config.ready()
        for verifying_key in private_relay_config.fxa_verifying_keys:
            if verifying_key['alg'] == 'RS256':
                verifying_key = jwt.algorithms.RSAAlgorithm.from_jwk(
                    json.dumps(verifying_key)
                )
                authentic_jwt = jwt.decode(
                    req_jwt,
                    verifying_key,
                    audience=social_app.client_id,
                    algorithms=['RS256']
                )

        if not authentic_jwt:
            raise Exception("Could not authenticate JWT with FXA key.")

    return authentic_jwt
```

And then I refactored into a `_verify_jwt_with_fxa_key` to reduce to code duplication:

```python
def _authenticate_fxa_jwt(req_jwt):
    private_relay_config = apps.get_app_config('privaterelay')
    authentic_jwt = _verify_jwt_with_fxa_key(req_jwt, private_relay_config)

    if not authentic_jwt:
        # FXA key may be old? re-fetch FXA keys and try again
        private_relay_config.ready()
        authentic_jwt = _verify_jwt_with_fxa_key(req_jwt, private_relay_config)
        if not authentic_jwt:
            raise Exception("Could not authenticate JWT with FXA key.")

    return authentic_jwt


def _verify_jwt_with_fxa_key(req_jwt, private_relay_config):
    social_app = SocialApp.objects.get(provider='fxa')
    for verifying_key in private_relay_config.fxa_verifying_keys:
        if verifying_key['alg'] == 'RS256':
            verifying_key = jwt.algorithms.RSAAlgorithm.from_jwk(
                json.dumps(verifying_key)
            )
            return jwt.decode(
                req_jwt,
                verifying_key,
                audience=social_app.client_id,
                algorithms=['RS256']
            )
```

Maybe the function names could be clearer?

2020-09-30 18:58 UTC, groovecoder commented on privaterelay/views.py
> +
If this ever returns `None`, then we'll see `Could not authenticate JWT with FXA key.` exception raised from `_authenticate_fxa_jwt`. Which I think has the same effect.

2020-09-30 19:01 UTC, say-yawn commented on privaterelay/views.py
> +            raise Exception("Could not authenticate JWT with FXA key.")
No I think this is fine. I was thinking if there was a cleaner way to retry and was bouncing the idea here 😓 One day we'll figure out how to design retries better, but today isn't the day.

2020-09-30 19:01 UTC, say-yawn approved these changes
LGTM

2020-09-30 19:10 UTC, merged