Support 8 bit content transfer encoding
mozilla/fx-private-relay pull request #709
Opened 2020-10-12 14:46 UTC by say-yawn

# About this PR
Support 8-bit Content Transfer Encoding by using `message_from_bytes` instead of `message_from_string`.

# Acceptance Criteria
- [ ] Email sent with 8-bit Content Transfer Encoding(CTE) no longer has broken body message
- [ ] Email sent with 8-bit CTE is converted to base64
- [ ] Follow-up issue created to document that emails coming in may not have UTF-8 as Content-Type's charset which can cause breakage

2020-10-15 20:56 UTC, groovecoder requested changes

2020-10-15 20:56 UTC, groovecoder commented on emails/views.py
> +    logger.error('body_message', extra={
Still need this `logger.error` line?

2020-10-15 20:56 UTC, groovecoder commented on emails/views.py
>      if html_content:
```suggestion
    if b_html_content:
```

2020-10-15 20:56 UTC, groovecoder commented on emails/views.py
>      text_content, html_content, attachments = _get_all_contents(email_message)
Can we remove this now if we're only using the `b_` variables?

2020-10-21 19:21 UTC, groovecoder commented
Code and spot-checks on dev look good.

2020-10-21 19:21 UTC, groovecoder approved these changes

2020-10-21 19:21 UTC, merged

2020-10-26 14:15 UTC, sv-hyacoub commented
We followed the steps from [#655](https://github.com/mozilla/fx-private-relay/issues/655) to verify the first test case of this PR, but the body of the email is still broken in every email service provider and the header of the email is displayed as following:
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

For the second test case we verified that special characters are not correctly displayed in email body section when sending emails from thunderbird to every email service provider via Firefox Relay. We confirm that the email body is displayed correctly now but the header of the email is displayed as following:
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

@say-yawn could you please take a look at out testing results and let's know your thoughts?