Move web-ext settings into config file
mozilla/fx-private-relay pull request #737
Opened 2020-11-20 19:26 UTC by pdehaan

Moves a bunch of duplicated <kbd>web-ext</kbd> configs into a separate config file to avoid duplicating in 3-4 places.
If you object to yet another new file, I think we can add it as a nested key in the extension/package.json.

Can't think of a better way yet to avoid using `sed` for string substitutions, unless we use Nunjucks/Liquid/lodash for simple templates (and then a combination of gitignore+web-ext ignoreFiles).

2020-11-20 21:55 UTC, groovecoder requested changes

2020-11-20 21:55 UTC, groovecoder commented on extension/web-ext-config.js
> +  artifactsDir: "../static/downloads/addon/latest/",
I actually want to stop building the artifacts into the static downloads folder. We never ended up using it.
```suggestion
```

2020-11-20 21:55 UTC, groovecoder commented on extension/package.json
> +    "build": "web-ext build && mv ../static/downloads/addon/latest/firefox_relay-*.zip ../static/downloads/addon/latest/firefox_relay.zip && npm run build:clean",
Trying to get away from `static/downloads`
```suggestion
    "build": "web-ext build && npm run build:clean",
```

2020-11-21 22:16 UTC, pdehaan commented
> Can't think of a better way yet to avoid using `sed` for string substitutions, unless we use Nunjucks/Liquid/lodash for simple templates (and then a combination of gitignore+web-ext ignoreFiles).

Yeah, I must be missing something, because this seems to actually _work_ (and is somewhat legible still):

```js
  "dependencies": {
    "liquidjs": "^9.16.1",
    "web-ext": "^5.2.0"
  },
  "devDependencies": {},
  "scripts": {
    "build": "node compile && web-ext build",
    "build:localhost": "PORT=:8000 npm run build",
    "build:dev": "HOST=https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net npm run build",
    "build:stage": "HOST=https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net npm run build",
    "build:prod": "HOST=https://relay.firefox.com npm run build",
    "lint": "web-ext lint",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

Where my ./extension/compile.js file is:

```js
const fs = require("fs");
const { Liquid } = require("liquidjs");

const engine = new Liquid({
  globals: {
    host: process.env.HOST || "http://127.0.0.1",
    port: process.env.PORT || "",
  },
});
const files = ["./manifest.json", "./popup.html", "./js/background.js"];

for (const file of files) {
  // Ie: load "./manifest.json.liquid", inject global vars, and write output to "./manifest.json".
  const output = engine.renderFileSync(`${file}.liquid`);
  fs.writeFileSync(file, output);
}
```

Still, a bit of back end juggling needed still to make sure .liquid templates don't get added to the add-on during <kbd>web-ext build</kbd> and we'd want to .gitignore the generated files so people don't try editing+committing those directly. But a possible future tweak (and fun Saturday hackin').

2020-11-22 15:49 UTC, groovecoder approved these changes

2020-11-22 15:49 UTC, merged