Integrate Fathom and email detector ruleset
mozilla/fx-private-relay pull request #743
Opened 2020-12-02 16:56 UTC by reuben

This PR vendors the [Fathom](https://github.com/mozilla/fathom) library and integrates our ruleset for detecting email fields. The ruleset works as follows:

1. First, all elements matching the selector `input[type=text],input[type=""],input:not([type])` are collected.
1. Then, the following rules are run against these elements, each rule returning a number:
    1. Rule "emailKeywords" returns the occurrences of the `/email|e-mail/gi` regex in the attributes and contents of the `<input>`.
    1. Rule "labelForInputMatchesEmail" returns the occurrences of the `/email/e-mail/gi` regex in the attributes of a `<label>` element associated with that input, if one exists, otherwise returns zero.
1. The values returned by the rules are combined into a single metric for each `<input>`, a weighted sum using the coefficients which were obtained by training with Fathom on a dataset of labeled pages. This metric is a probability.
1. In the function `detectEmailInputs` we take every element with a metric value `> 50%` as a positive detection of an email field and return it.

Opening the PR took me a bit more time than I expected as I encountered a false positive as I was opening it :) GitHub pre-populates the title field for PRs with the commit message, which in this case included "email" in it, so the extension put a Relay icon there. I've modified the ruleset to ignore the `value` attribute to avoid such false positives, but in general this is a side effect of how we collected training data for the ruleset. It's possible that there are more such cases in the long tail which we have not identified due to not having seen them yet.

There's also a FIXME comment which I added as I was debugging this PR, and is still here (in `add_input_icon.js`). Let me know what you think, I can move that into an issue in the repo.

2020-12-02 19:13 UTC, birdsarah commented
Reuben's discovery this morning of a new false positive has taken the shine off the confidence I had yesterday in our meeting. It highlights the limitations of the dataset we gathered. I don't believe we can gather a better dataset that will address these kind of discoveries. 

That said, I still feel good. In summary:
- we have two simple and easy to understand rules, so it should be relatively easy to intuit where we're likely to see problems
- our training results are excellent with almost only 1 false positive and only a handful of false negatives and we optimized for minimizing false positives over a few false negatives
- training is only as good as the dataset we use and our dataset was gathered by finding sign-up and log-in forms on top 200 sites along with newsletter signups and the occasional other contact form where I found them. we may find, like reuben did this morning, that we have a systematic problem as we have not collected a specific class/genre of fields to fill or not fill in. i do not believe that we can gather a better scraping-style, simple dataset that will address these kind of biases.

I will have all of this in a proper write-up to share with the team this week.

2020-12-05 14:11 UTC, groovecoder requested changes
Some code suggestions that are mostly semantic function or variable name changes just to make the code a bit more explicit and clear.

I also found another FP on the relay dashboard itself. :) 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/71928/101245278-552cdb80-36d1-11eb-8120-9c8d39e4d807.png">

The markup is:

```
<input data-label="zoom.us" type="text" maxlength="50" value="" aria-label="Edit the label for this alias" class="relay-email-address-label ff-Met" style="padding-right: 50px;">
```

We could try to adjust for this in the detection code. Or, we could try to just NOT run the content script on our own site?

2020-12-06 07:00 UTC, birdsarah commented
oof another false positive. thanks for the report @groovecoder.

@groovecoder I'd like to have another round of discussions with @ilanasegall and reuben before merging.

2020-12-06 07:01 UTC, birdsarah commented
@reuben, I'd like to try a ruleset where we only look for placeholder value rather than all attributes.

2020-12-07 19:46 UTC, birdsarah commented on extension/popup.html
>      <script src="js/add_input_icon.js"></script>
Suggest doing this change in a separate one-line PR, to keep this code-change clean. (I imagine this PR commit being a useful reference for "how to integrate fathom") so reducing future mental overhead.

2020-12-11 15:55 UTC, reuben commented on extension/popup.html
>      <script src="js/add_input_icon.js"></script>
I moved that fix to #754

2020-12-11 22:00 UTC, birdsarah commented
We have re-worked the ruleset to be more conservative. We have re-trained and tested with a new batch of samples. The official test results say that the model is perfect - 100% precision and recall. That's an artifact of the data set though. We know that there will be false positives. We believe that they will be rare. They occur specifically when there's an input field in a very "email"-y setting.

I'm finishing up the report to give you a nuanced picture.

2020-12-15 20:45 UTC, groovecoder commented
Is this still a draft/WIP? Should I go ahead and review it?

2020-12-17 18:05 UTC, erikrose commented
Since you mentioned you were only using 2 rules (though now I see 3), I'll throw this out:

Fathom does best with many small, simple rules, because it gives the trainer more degrees of freedom. Just something to keep in mind. For example, I've been known to bust up a rule that looks in multiple attributes into several that look in 1 attr each. I've also been known to put each alternation of a regex into its own rule. There's no need to carry this to its extreme, but it can get you unstuck sometimes if you're not getting the scores you want. We have found the occasional regex alternation that is responsible for a large portion of false positives.

Cheers!

2020-12-18 09:05 UTC, birdsarah commented
We have discussed the model with Bianca, Se Yeon, and Luke. The Relay team has been emailed the final report. In summary the results are:

- Result 1: Of the email fields that we observe in our dataset, Relay in its current state will identify ~50% of them.
- Result 2: The new fathom model detect ~80% of email fields in our dataset, that are not of type='email', with a very low false positive rate.
- Result 3: Combining results 1 and 2. Including the fathom model into relay will increase detection of email fields from ~50% to ~90%.
- We have a known false positive with the Yahoo / AOL sign-up form. This appears to be acceptable. It could be hard-coded out if users report annoyance.
- There may be other pathological cases that we do not know about due to biases in our datasets and testing, although we have tried to find them.

2021-01-04 22:09 UTC, groovecoder requested changes

2021-01-05 17:44 UTC, birdsarah commented
@groovecoder I tested your changes on the data. All looks good. I committed it. 

It did not change the performance stats for time to evaluate per tag that fathom spits out. I'm guessing that's because there are generally very few items to iterate through.

2021-01-05 17:45 UTC, reuben commented
Thanks @birdsarah!

2021-01-06 15:28 UTC, groovecoder commented
Thanks @birdsarah . Probably a micro-optimization, but I also like removing any and all mutable variables if I can. I'm a wannabe-functional engineer. (sometimes)

2021-01-06 15:28 UTC, merged