add ongoing, periodic PMF & NPS surveys to the top banner
mozilla/fx-private-relay pull request #791
Opened 2021-02-11 19:58 UTC by groovecoder

2021-02-11 21:43 UTC, lesleyjanenorton commented
Let's add a media query to hide this on narrower windows/smaller devices.

2021-02-11 22:44 UTC, groovecoder commented
Added media query.

2021-02-12 16:18 UTC, maxxcrawford requested changes
I have some design notes but can help make those changes if you'd like! 

The bigger issue is that uBlock Origin is blocking `/js/analytics.js` from loading, which is obscuring part of the survey. 

I recommend using CSS to hide the survey (for those who are selected for the survey) and unhide it via JS in the `/js/analytics.js` file.

2021-02-12 16:22 UTC, maxxcrawford requested changes

2021-02-12 16:22 UTC, maxxcrawford commented on static/js/analytics.js
> +  resetBodyPadding();
I recommend adding a function here to unhide the survey for selected users.

2021-02-12 16:22 UTC, maxxcrawford commented on static/css/style.css
> +.recruitment-banner, .micro-survey-banner {
Hide the survey by default with CSS:

```suggestion
.recruitment-banner, .micro-survey-banner {
  display: none;
```

2021-02-12 20:19 UTC, maxxcrawford commented
Revised style of the survey bar: 
- Increased background contrast
- Made clickable elements look more like buttons (padding, background color, rounded corners) 

PMF: 
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/2692333/107818375-21a7a680-6d3d-11eb-800d-f89c22694a01.png">

NPS:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/2692333/107818378-23716a00-6d3d-11eb-9ab2-16fc6ba1f25d.png">

2021-02-17 16:38 UTC, groovecoder commented on static/js/analytics.js
> +              metric3: eventData.npsValue,
Note: these metric indices are defined in GA:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/71928/108236236-47052d80-710c-11eb-9148-67e0f0850f88.png">

2021-02-17 16:38 UTC, groovecoder commented on static/js/analytics.js
> +      }
Note: these metric indices are defined in GA:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/71928/108236236-47052d80-710c-11eb-9148-67e0f0850f88.png">

2021-02-17 22:21 UTC, maxxcrawford approved these changes
LGTM!  🚀 

I can't speak to the analytics, so let's be sure to confirm live data is capturing/reporting as expected once deployed.

2021-02-18 16:21 UTC, merged