Improve success message for sign in/out
mozilla/fx-private-relay pull request #915
Opened 2021-07-15 18:57 UTC by codemist

Implemented new design for the sign in/out success message. Figma reference: 

![image](https://user-images.githubusercontent.com/13066134/125842258-e4f95b2d-f259-43ad-b4e7-612afeb532b1.png)

2021-07-16 20:58 UTC, groovecoder requested changes

2021-07-16 20:58 UTC, groovecoder commented on privaterelay/templates/home.html
> +
```suggestion
```

2021-07-16 20:58 UTC, groovecoder commented on privaterelay/templates/includes/header.html
> +
```suggestion
```

2021-07-16 20:58 UTC, groovecoder commented on privaterelay/templates/profile.html
> +<!--{% include "includes/messages.html" with messages=messages %}-->
```suggestion
```

2021-07-20 20:04 UTC, groovecoder commented
Looks good but has some conflicts to resolve? Are you comfortable doing that yourself?

2021-07-21 00:31 UTC, codemist commented
Looks fine here: 
![image](https://user-images.githubusercontent.com/13066134/126411782-e3863b3e-f3d8-4aea-9e34-0a0215c7befc.png)

I can get on a meeting with Maxx about resolving conflicts when he's back since I've not done that before.

2021-07-22 16:41 UTC, closed without merging

2021-07-22 16:43 UTC, maxxcrawford commented
Test