Fix #926 - Remove search icon when no alias
mozilla/fx-private-relay pull request #937
Opened 2021-07-20 18:22 UTC by codemist

Added template tag to disable search icon when there are no aliases listed.

2021-07-20 20:43 UTC, groovecoder requested changes

2021-07-20 20:43 UTC, groovecoder commented on privaterelay/templates/includes/dashboard-filter.html
> +        {% if relay_addresses|length >= 1 %}
I think a python list is evaluated as `False` if it has no elements, so you could change this to:
```suggestion
        {% if relay_addresses %}
```

2021-07-21 00:23 UTC, codemist commented
I just selected _commit changes_ to your review - am I allowed to do that? Does that change my commit?

2021-07-21 17:04 UTC, maxxcrawford approved these changes
Clean logic. Ship it!

2021-07-21 17:04 UTC, merged