Fix #956 - Add Sign Up btn in mobile menu dropdown
mozilla/fx-private-relay pull request #982
Opened 2021-07-30 16:57 UTC by codemist

- I added the sign up button on the mobile dropdown menu for the landing page
- Set the background of the dropdown to white (not the toggle for now), in accordance with Eduardo's new design (see below)

Preview:
![image](https://user-images.githubusercontent.com/13066134/127686573-2626831b-9051-4e75-a107-8f70946feb16.png)

Figma reference:
![image](https://user-images.githubusercontent.com/13066134/127686614-4cbe0191-d43e-49f6-bbb6-faa70e3da3da.png)

Note: Still need to have a conversation with Eduardo about keeping the bento box.

2021-07-30 17:14 UTC, maxxcrawford requested changes

2021-07-30 17:14 UTC, maxxcrawford commented on static/scss/partials/main.scss
> +  background: $color-white;
Let's just focus on the text link change for now. Can you revert all color updates? Let's update the UI all at once, when it's locked in with Eduardo.

2021-07-30 17:21 UTC, codemist commented
@maxxcrawford 

Gotcha - here's a preview:
![image](https://user-images.githubusercontent.com/13066134/127689214-2aa51228-29c9-420f-a65a-3f3531d70e32.png)

2021-08-03 01:13 UTC, maxxcrawford approved these changes
Looks good!

2021-08-03 01:14 UTC, merged